# Generated by Django 4.0.6 on 2022-08-16 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderplace',
            old_name='ordered_data',
            new_name='ordered_date',
        ),
    ]
